openapi: 3.0.0
info:
  title: testProject API for Hospyta
  description: API for user authentication, posts, and comments
  version: 1.0.0
servers:
  - url: http://localhost:3600/users
paths:
  /register:
    post:
      summary: Register a new user
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
                password:
                  type: string
                confirmPassword:
                  type: string
                profileImage:
                  type: string
                  format: binary
      responses:
        '201':
          description: Registration successful
        '400':
          description: Bad request
        '500':
          description: Internal server error
  /verifyAccount:
    get:
      summary: Verify user account
      parameters:
        - name: id
          in: query
          required: true
          schema:
            type: string
        - name: token
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Account confirmed
        '401':
          description: Unauthorized
        '500':
          description: Internal server error
  /renewLink:
    post:
      summary: Renew registration link
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
      responses:
        '201':
          description: Registration successful
        '401':
          description: Unauthorized
        '500':
          description: Internal server error
  /login:
    post:
      summary: User login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: Login successful
        '401':
          description: Unauthorized
        '500':
          description: Internal server error
  /forgotPassword:
    post:
      summary: Forgot password
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
      responses:
        '201':
          description: Reset link sent
        '401':
          description: Unauthorized
        '500':
          description: Internal server error
  /confirmReset:
    get:
      summary: Confirm reset link
      parameters:
        - name: id
          in: query
          required: true
          schema:
            type: string
        - name: token
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Valid link
        '401':
          description: Unauthorized
        '500':
          description: Internal server error
  /resetPassword:
    post:
      summary: Reset password
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                password:
                  type: string
      responses:
        '200':
          description: Password reset successful
        '401':
          description: Unauthorized
        '500':
          description: Internal server error
  /allEntries:
    get:
      summary: Get all entries
      responses:
        '200':
          description: List of all entries
        '401':
          description: Unauthorized
        '500':
          description: Internal server error
  /myEntries:
    get:
      summary: Get user's entries
      responses:
        '200':
          description: List of user's entries
        '401':
          description: Unauthorized
        '500':
          description: Internal server error
  /myEntry:
    get:
      summary: Get a specific entry
      parameters:
        - name: _id
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Entry details
        '401':
          description: Unauthorized
        '500':
          description: Internal server error
  /createEntry:
    post:
      summary: Create a new entry
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                title:
                  type: string
                content:
                  type: string
                category:
                  type: string
                image:
                  type: string
                  format: binary
      responses:
        '201':
          description: Entry created successfully
        '400':
          description: Bad request
        '500':
          description: Internal server error
  /updateEntry:
    put:
      summary: Update an entry
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                _id:
                  type: string
                title:
                  type: string
                content:
                  type: string
                category:
                  type: string
                image:
                  type: string
                  format: binary
      responses:
        '200':
          description: Edit successful
        '401':
          description: Unauthorized
        '500':
          description: Internal server error
  /deleteEntry:
    delete:
      summary: Delete an entry
      parameters:
        - name: _id
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Delete successful
        '401':
          description: Unauthorized
        '500':
          description: Internal server error
  /entries/{id}/upvote:
    post:
      summary: Upvote an entry
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Upvoted successfully
        '404':
          description: Entry not found
        '500':
          description: Internal server error
  /entries/{id}/downvote:
    post:
      summary: Downvote an entry
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Downvoted successfully
        '404':
          description: Entry not found
        '500':
          description: Internal server error
  /entries/sorted:
    get:
      summary: Get sorted posts
      parameters:
        - name: category
          in: query
          schema:
            type: string
      responses:
        '200':
          description: Sorted posts
        '500':
          description: Internal server error
  /addComments:
    post:
      summary: Add a comment
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                entryId:
                  type: string
                content:
                  type: string
      responses:
        '201':
          description: Comment added successfully
        '401':
          description: Unauthorized
        '500':
          description: Internal server error
  /replyComments:
    post:
      summary: Reply to a comment
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                commentId:
                  type: string
                content:
                  type: string
      responses:
        '201':
          description: Reply added successfully
        '401':
          description: Unauthorized
        '500':
          description: Internal server error
  /comments/{postId}:
    get:
      summary: Get comments for a post
      parameters:
        - name: postId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: List of comments
        '404':
          description: No comments found
        '500':
          description: Internal server error
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    User:
      type: object
      properties:
        _id:
          type: string
        profileImage:
          type: string
        name:
          type: string
        email:
          type: string
        password:
          type: string
        confirmPassword:
          type: string
        verified:
          type: boolean
    Entry:
      type: object
      properties:
        _id:
          type: string
        image:
          type: string
        title:
          type: string
        content:
          type: string
        category:
          type: string
        user:
          type: string
        upvotes:
          type: number
        downvotes:
          type: number
    Comment:
      type: object
      properties:
        _id:
          type: string
        entry:
          type: string
        user:
          type: string
        content:
          type: string
        replies:
          type: array
          items:
            type: string
security:
  - bearerAuth: []
